/**
 * LoadingSpinner — YOUR-TEAM logo-mark Lottie spinner.
 *
 * Source JSON: ./jl-spinner.lottie.json (generated by /tmp/svg_to_lottie.py from public/jl-logo.svg).
 * Skill: ~/.claude/skills/lottie-animator (obeskay/lottie-animator-skill).
 * Adopters: tracked in DESIGN_CATALOG.md.
 *
 * 2.4s loop · 60fps · sequential trace (L1 → L2) → red fill → hold → reset.
 * Respects `prefers-reduced-motion` via Lottie's autoplay pause.
 */

import React from 'react';
import Lottie from 'lottie-react';
import animationData from './jl-spinner.lottie.json';
import { cn } from '@/lib/utils';

interface LoadingSpinnerProps {
  /** Size variant: sm (24px), md (40px), lg (64px) */
  size?: 'sm' | 'md' | 'lg';
  className?: string;
  /** Optional text label below the spinner */
  label?: string;
}

const SIZES = {
  sm: 24,
  md: 40,
  lg: 64,
};

const prefersReducedMotion =
  typeof window !== 'undefined' &&
  window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

export const LoadingSpinner: React.FC<LoadingSpinnerProps> = ({
  size = 'md',
  className,
  label,
}) => {
  const px = SIZES[size];
  return (
    <div
      role="status"
      aria-live="polite"
      aria-label={label ?? 'Loading'}
      className={cn('flex flex-col items-center justify-center gap-3', className)}
    >
      <Lottie
        animationData={animationData}
        loop
        autoplay={!prefersReducedMotion}
        style={{ width: px, height: px }}
        aria-hidden="true"
      />
      {label && (
        <span className="text-sm font-medium text-zinc-700">
          {label}
        </span>
      )}
    </div>
  );
};
