#!/usr/bin/env bash
#
# W05 Drift Detector — weekly digest
#
# Compares current HEAD against `pre-refactor-baseline` tag and the initial
# baseline numbers in W05_DRIFT_BASELINE.md. Writes a markdown digest to
#   docs/99-refactor/_system/research/W05_DRIFT_WEEKLY_<YYYY-MM-DD>.md
#
# Run manually every Friday — not wired to cron (per W05 card guardrails).
# Usage:  bash scripts/drift_weekly_digest.sh
#
# Prereqs:
#   - dependency-cruiser (devDependency)
#   - node (used for JSON parsing; no jq dependency)
#   - git tag `pre-refactor-baseline` (created in W05 Phase 1)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

BASELINE_TAG="pre-refactor-baseline"
OUT_DIR="docs/99-refactor/_system/research"
TODAY="$(date +%Y-%m-%d)"
OUT_FILE="$OUT_DIR/W05_DRIFT_WEEKLY_${TODAY}.md"
TMP_JSON="$(mktemp -t drift_weekly.XXXXXX.json)"
trap 'rm -f "$TMP_JSON"' EXIT

if ! git rev-parse --verify "$BASELINE_TAG" >/dev/null 2>&1; then
  echo "ERROR: tag '$BASELINE_TAG' not found. Run Phase 1 of W05_DRIFT_DETECTOR.md first." >&2
  exit 1
fi

BASELINE_SHA="$(git rev-parse "$BASELINE_TAG")"
HEAD_SHA="$(git rev-parse HEAD)"
HEAD_SHORT="$(git rev-parse --short HEAD)"

CURRENT_FILES="$(git ls-tree -r HEAD --name-only | grep -cE '^(src/|supabase/|scripts/|tests/|docs/)' || true)"

ADDED="$(git diff --name-status "$BASELINE_TAG" HEAD -- 'src/*' 'supabase/*' 'scripts/*' 'tests/*' 'docs/*' | awk '$1=="A"' | wc -l | tr -d ' ')"
MODIFIED="$(git diff --name-status "$BASELINE_TAG" HEAD -- 'src/*' 'supabase/*' 'scripts/*' 'tests/*' 'docs/*' | awk '$1=="M"' | wc -l | tr -d ' ')"
DELETED="$(git diff --name-status "$BASELINE_TAG" HEAD -- 'src/*' 'supabase/*' 'scripts/*' 'tests/*' 'docs/*' | awk '$1=="D"' | wc -l | tr -d ' ')"
RENAMED="$(git diff --name-status "$BASELINE_TAG" HEAD -- 'src/*' 'supabase/*' 'scripts/*' 'tests/*' 'docs/*' | awk '$1 ~ /^R/' | wc -l | tr -d ' ')"

npx depcruise --config .dependency-cruiser.cjs --output-type json src >"$TMP_JSON" 2>/dev/null || true

if [ ! -s "$TMP_JSON" ]; then
  echo "ERROR: depcruise produced no output. Run 'npm run drift:check' to diagnose." >&2
  exit 1
fi

METRICS="$(node - <<'NODE' "$TMP_JSON"
const fs = require('fs');
const r = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const s = r.summary;
const byRule = {};
for (const v of s.violations) byRule[v.rule.name] = (byRule[v.rule.name] || 0) + 1;

const dependents = {};
for (const mod of r.modules || []) {
  for (const dep of mod.dependencies || []) {
    const t = dep.resolved;
    if (!t) continue;
    if (!/^src\/components\/[^/]+\/[^/]+\.(ts|tsx)$/.test(t)) continue;
    if (/^src\/components\/ui\//.test(t)) continue;
    dependents[t] = dependents[t] || new Set();
    dependents[t].add(mod.source);
  }
}
const overshared = Object.entries(dependents)
  .map(([p, set]) => [p, set.size])
  .filter(([, n]) => n > 3)
  .sort((a, b) => b[1] - a[1]);

const top10Violators = {};
for (const v of s.violations) top10Violators[v.from] = (top10Violators[v.from] || 0) + 1;
const topFiles = Object.entries(top10Violators).sort((a, b) => b[1] - a[1]).slice(0, 10);

console.log(JSON.stringify({
  totalCruised: s.totalCruised,
  totalDependenciesCruised: s.totalDependenciesCruised,
  violationsTotal: s.violations.length,
  errors: s.error,
  warnings: s.warn,
  byRule,
  oversharedCount: overshared.length,
  oversharedTop: overshared.slice(0, 10),
  topViolatorFiles: topFiles,
}));
NODE
)"

mkdir -p "$OUT_DIR"

BASELINE_VIOLATIONS=5
BASELINE_OVERSHARED=16

python3 - "$METRICS" "$BASELINE_SHA" "$HEAD_SHA" "$HEAD_SHORT" "$TODAY" "$CURRENT_FILES" "$ADDED" "$MODIFIED" "$DELETED" "$RENAMED" "$BASELINE_VIOLATIONS" "$BASELINE_OVERSHARED" "$OUT_FILE" <<'PY'
import json, sys, datetime

(_, metrics_json, baseline_sha, head_sha, head_short, today,
 current_files, added, modified, deleted, renamed,
 baseline_violations, baseline_overshared, out_file) = sys.argv

m = json.loads(metrics_json)

def delta(now, base):
    diff = now - base
    if diff == 0: return "±0"
    return f"{'+' if diff > 0 else ''}{diff}"

lines = []
lines.append(f"# W05 Drift — weekly digest {today}")
lines.append("")
lines.append(f"**Created**: {today} SGT  ")
lines.append(f"**Last Updated**: {today} SGT — generated by `scripts/drift_weekly_digest.sh`.  ")
lines.append(f"**Status**: 🟢 Production  ")
lines.append(f"**Priority**: 🟡 High  ")
lines.append("")
lines.append("## 📋 Overview")
lines.append("")
lines.append(f"Comparison: `pre-refactor-baseline` (`{baseline_sha[:10]}`) → HEAD (`{head_short}`).")
lines.append(f"Review weekly on Friday. Advisory — does not block the build. Baseline reference: [W05_DRIFT_BASELINE.md](W05_DRIFT_BASELINE.md).")
lines.append("")
lines.append("## 📚 Related Documentation")
lines.append("")
lines.append("- [W05_DRIFT_BASELINE.md](W05_DRIFT_BASELINE.md)")
lines.append("- [W05_DRIFT_DETECTOR.md](../workflows/W05_DRIFT_DETECTOR.md)")
lines.append("- [.dependency-cruiser.cjs](../../../../.dependency-cruiser.cjs)")
lines.append("")
lines.append("## File drift since baseline")
lines.append("")
lines.append("| Metric | Value |")
lines.append("|---|---|")
lines.append(f"| Baseline SHA | `{baseline_sha}` |")
lines.append(f"| HEAD SHA | `{head_sha}` |")
lines.append(f"| Tracked files at HEAD (src/supabase/scripts/tests/docs) | {current_files} |")
lines.append(f"| Added | {added} |")
lines.append(f"| Modified | {modified} |")
lines.append(f"| Deleted | {deleted} |")
lines.append(f"| Renamed | {renamed} |")
lines.append("")
lines.append("## Drift-rule violations")
lines.append("")
total = m['violationsTotal']
lines.append(f"| Scope | Baseline | This week | Δ |")
lines.append("|---|---|---|---|")
lines.append(f"| Total violations | {baseline_violations} | {total} | {delta(total, int(baseline_violations))} |")
lines.append(f"| Errors | 5 | {m['errors']} | {delta(m['errors'], 5)} |")
lines.append(f"| Warnings | 0 | {m['warnings']} | {delta(m['warnings'], 0)} |")
lines.append(f"| Modules cruised | 992 | {m['totalCruised']} | {delta(m['totalCruised'], 992)} |")
lines.append("")
lines.append("### By rule")
lines.append("")
if not m['byRule']:
    lines.append("_No rule violations at HEAD. Clean._")
else:
    lines.append("| Rule | Hits |")
    lines.append("|---|---|")
    for name, n in sorted(m['byRule'].items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{name}` | {n} |")
lines.append("")
lines.append("### Top 10 offender files")
lines.append("")
if not m['topViolatorFiles']:
    lines.append("_None — clean slate._")
else:
    lines.append("| Hits | File |")
    lines.append("|---|---|")
    for f, n in m['topViolatorFiles']:
        lines.append(f"| {n} | `{f}` |")
lines.append("")
lines.append("## Oversharing watch (W07 primitive candidates)")
lines.append("")
lines.append(f"Non-`ui/` components in `src/components/<sub>/` with >3 dependents. Baseline: {baseline_overshared}. This week: {m['oversharedCount']} ({delta(m['oversharedCount'], int(baseline_overshared))}).")
lines.append("")
if not m['oversharedTop']:
    lines.append("_No overshared components this week._")
else:
    lines.append("| Dependents | File |")
    lines.append("|---|---|")
    for f, n in m['oversharedTop']:
        lines.append(f"| {n} | `{f}` |")
lines.append("")
lines.append("## Reading this digest")
lines.append("")
lines.append("- **Violations trending up** — investigate the added/modified files; a new module may be bypassing shared primitives.")
lines.append("- **New rule hits** (rules that were 0 at baseline) — priority signal; the refactor just broke a boundary.")
lines.append("- **Oversharing growth** — component cluster getting duplicated; consider promoting to a W07 primitive.")
lines.append("- **File drift (added/deleted)** — cross-check against `MODULE_MAP.md` — new modules must appear there.")
lines.append("")
lines.append("_Generated by [scripts/drift_weekly_digest.sh](../../../../scripts/drift_weekly_digest.sh) on demand — not cron-scheduled._")

with open(out_file, 'w') as fh:
    fh.write("\n".join(lines))
print(f"wrote {out_file}")
PY

echo ""
echo "Digest ready: $OUT_FILE"
echo "  violations:    $(echo "$METRICS" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8")); console.log(d.violationsTotal)')"
echo "  added files:   $ADDED"
echo "  deleted files: $DELETED"
